### ISSUE TITLE
utf8 error

### ISSUE THREAD

**Issue by dmd** [rovest/Bear-Markdown-Export#4]
```
Traceback (most recent call last):
  File "/Users/dmd/Dropbox/code/Bear-Markdown-Export/bear_export_sync.py", line 711, in <module>
    main()
  File "/Users/dmd/Dropbox/code/Bear-Markdown-Export/bear_export_sync.py", line 117, in main
    sync_md_updates()
  File "/Users/dmd/Dropbox/code/Bear-Markdown-Export/bear_export_sync.py", line 459, in sync_md_updates
    md_text = read_file(md_file)
  File "/Users/dmd/Dropbox/code/Bear-Markdown-Export/bear_export_sync.py", line 364, in read_file
    file_content = f.read()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 368: invalid start byte
```

**Comment by rovest** [comment]
Hi @dmd 
Sorry for very late reply.

But you happen to have more info on thiis issue?

1. Has it happened again?
2. Do you now what kind of file or character that triggered it?
3. Do you still have a sample of file, or can you reproduce it?
4. If it’s a recurring provlem, could an error handler solve the problem? What do you think?

Thanks, and hope the new 1.7.2 version works better for you.

Please let me know if you find other issues.

Al the best,
Roar

**Comment by dmd** [comment]
I can't seem to reproduce this now. I'll reopen if I can in the future.
